APPLICATION = crypto_aesctr

BOARD ?= scum-devkit

USEMODULE += crypto
USEMODULE += crypto_aes_128
USEMODULE += cipher_modes
USEMODULE += fmt
USEMODULE += shell

RIOTBASE ?= $(CURDIR)/../RIOT

include $(RIOTBASE)/Makefile.include
