name: Build

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build ai_emlearn application
        run: |
          docker run --rm -v ${{ github.workspace }}:/riotbuild riot/riotbuild:latest make -C /riotbuild/ai_emlearn
      - name: Build crypto_aesctr application
        run: |
          docker run --rm -v ${{ github.workspace }}:/riotbuild riot/riotbuild:latest make -C /riotbuild/crypto_aesctr
